### ISSUE TITLE
Android App immediately crashes on emulator and real device

### ISSUE THREAD

**Issue by michpohl** [wzieba/KMM-in-exsiting-project-template#12]
Hi, I hope this is useful for you...
Really appreciate the repo!
I cloned your template and ran the test apps for Android and iOS. Running the androidApp from both Android Studio builds successfully, but the Android app immediately crashes on both an emulator and a real device (Tested this with Android 10 so far). This is the stacktrace:
```
2021-04-15 15:19:11.677 17111-17111/com.automattic.myapplication.androidApp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.automattic.myapplication.androidApp, PID: 17111
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.automattic.myapplication.androidApp/com.automattic.myapplication.androidApp.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.automattic.myapplication.androidApp.MainActivity" on path: DexPathList[[zip file "/data/app/com.automattic.myapplication.androidApp-FaKZaENNyJLsbQh6wYYHfA==/base.apk"],nativeLibraryDirectories=[/data/app/com.automattic.myapplication.androidApp-FaKZaENNyJLsbQh6wYYHfA==/lib/x86, /system/lib, /system/product/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.automattic.myapplication.androidApp.MainActivity" on path: DexPathList[[zip file "/data/app/com.automattic.myapplication.androidApp-FaKZaENNyJLsbQh6wYYHfA==/base.apk"],nativeLibraryDirectories=[/data/app/com.automattic.myapplication.androidApp-FaKZaENNyJLsbQh6wYYHfA==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1243)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

Obviously, the MainActivity is registered correctly in the AndroidManifest, so I'm confused where this error comes from, since that is the typical source for this kind of problem. A freshly created KMM project runs without issues but I was unable to find the difference. Not super experienced with Multiplatform yet, so I'm hitting a wall here...Could you maybe investigate if there's an error in the template ( does it run properly for you?)

**Comment by wzieba** [comment]
Thank you @michpohl for checking template, I'm super glad that you find it useful!

I'll check for this issue and confirm if it happens for me too.

**Comment by wzieba** [comment]
@michpohl I confirm the crash. It appears that I forgot to apply `kotlin-android` plugin to the Android module.

Thank you for the report! I hope it'll work for you now. If not, feel free to re-open this issue.
